import assert from 'node:assert/strict';
import { scoreOpportunity } from './vetting.mjs';
import { buildDraft } from './listing-drafts.mjs';
import { buildHealthReport, deadlineAlerts } from './monitor.mjs';
import { approvalCard } from './telegram-adapter.mjs';
import { normalizeInventory, normalizeOrders } from './normalizers.mjs';
import { scoreMarketSignal } from './market-signals.mjs';
import { rankSuppliers } from './suppliers.mjs';
import { recommendPrice } from './pricing.mjs';
import { profitReport } from './profit-report.mjs';
import { scoreDiscoveredProducts } from './product-discovery.mjs';
import { signAliExpress } from './aliexpress-adapter.mjs';

const preferred=scoreOpportunity({salePrice:50,supplierCost:20,supplierShipping:5,monthlySales:10,shipDays:5,handlingDays:2,stockConfidence:90});
assert.equal(preferred.preferredTarget,true); assert.equal(preferred.decision,'review');
const volume=scoreOpportunity({salePrice:20,supplierCost:10,supplierShipping:2,monthlySales:50,shipDays:7,handlingDays:3,stockConfidence:80});
assert.equal(volume.highVolumeException,true); assert.equal(volume.decision,'review');
const health=buildHealthReport({transactionDefectRate:5.51,trackingValidatedPct:66.04});
assert.equal(health.sellerLevel,'at-risk'); assert.equal(health.liveActionsRecommended,false);
const alerts=deadlineAlerts([{orderId:'urgent',shipBy:'2026-09-21T20:00:00Z'},{orderId:'ok',shipBy:'2026-09-23T20:00:00Z'}],new Date('2026-09-21T12:00:00Z'));
assert.equal(alerts.length,1); assert.equal(alerts[0].level,'urgent');
const draft=buildDraft({name:'Test item',category:'Games',salePrice:30,supplierShipping:8,shipDays:20,supplierAuthorized:false});
assert.equal(draft.shippingIncluded,true); assert.ok(draft.riskFlags.includes('Long supplier transit')); assert.ok(draft.riskFlags.includes('Supplier authorization not verified'));
assert.equal(draft.approvalRequired,true); assert.equal(draft.publishable,false); assert.equal(draft.shipping.costIncludedInPrice,true); assert.ok(draft.estimatedDelivery.maximumDays>draft.estimatedTransitDays);
assert.match(approvalCard({action:'publish_listing',item:'Test item',status:'pending',id:'test-id'}),/Approval ID: test-id/);
assert.equal(normalizeInventory({inventoryItems:[{sku:'x',product:{title:'Test'},availability:{shipToLocationAvailability:{quantity:4}}} ]})[0].quantity,4);
assert.equal(normalizeOrders({orders:[{orderId:'o',pricingSummary:{total:{value:'12.50',currency:'USD'}},lineItems:[]} ]})[0].total,12.5);
assert.equal(scoreMarketSignal({sales30d:50,views30d:1000,watchers30d:80,competitorCount:4}).interpretation,'strong demand');
const ranked=rankSuppliers([{name:'slow',cost:10,shipping:2,handlingDays:10,transitDays:20,stockConfidence:90,authorized:true},{name:'fast',cost:12,shipping:3,handlingDays:2,transitDays:5,stockConfidence:90,authorized:true}]);
assert.equal(ranked[0].name,'fast'); assert.equal(ranked[0].eligible,true);
const us=rankSuppliers([{name:'us-stock',cost:14,shipping:3,handlingDays:2,transitDays:3,stockConfidence:90,rating:4.8,reviewCount:200,shipFrom:'United States',authorized:true}])[0];
assert.equal(us.usWarehouse,true); assert.equal(us.eligible,true);
assert.equal(recommendPrice({supplierCost:10,supplierShipping:2,targetProfit:10,marketMedian:30}).shippingIncluded,true);
assert.equal(profitReport([{sku:'x',revenue:30}],{x:10},14).summary.profit,15.8);
const discovered=scoreDiscoveredProducts([{name:'Fast US candidate',marketPrice:39.99,cost:18,shipping:4,monthlySales:60,rating:4.8,reviewCount:200,stockConfidence:90,shipFrom:'United States',handlingDays:2,transitDays:4}])[0];
assert.equal(discovered.decision,'review'); assert.equal(discovered.usWarehouse,true); assert.equal(discovered.highVolumeException,true);
assert.equal(signAliExpress({b:'2',a:'1'},'secret'),signAliExpress({a:'1',b:'2'},'secret'));
console.log('All store-agent tests passed');
